### ISSUE TITLE
Microsoft.Maui.Controls.ShellSection: Warning: Failed to Create Content For: D_FAULT_EmbeddedBrowser

### ISSUE THREAD

**Issue by MrJackSpade** [0xc3u/Indiko.Maui.Controls.Markdown#10]
When clicking a link generated through the `OnHyperLinkClicked` event, attempting to navigate a `WebView` fails.

This is only an issue when clicking hyperlinks, as the same Url/ContentView/WebView function perfectly fine when opened through other events like button clicks.

I don't know if its something to do with the scope of the execution or not.

**Comment by MrJackSpade** [comment]
I've found the actual source of the issue.

The problem is that the event handler is static. When rendering multiple components on the same page, this causes each component to register to a shared event handler instead of its own event handler. So if you have 4x `MarkdownView` components, each click event fires 4x.

When triggering multiple `WebView` loads at the same time, each successive load steps on the previous, which causes the first three to break since the page isn't accessible anymore due to new pages having loaded.

The solution appears to be to simply remove the `static` keyword from the event handler 

https://github.com/0xc3u/Indiko.Maui.Controls.Markdown/blob/349b69b3311f096f6f401639e4ab47d978dbb662/src/Indiko.Maui.Controls.Markdown/MarkdownView.cs#L18C9-L18C61

**Comment by 0xc3u** [comment]
Thank you for pointing out the issue with the static event handler.
We have removed it in version 1.0.11, which is now available on nudet.org.
