### ISSUE TITLE
Embedded images don't render SVGs

### ISSUE THREAD

**Issue by ivanbportugal** [0xc3u/Indiko.Maui.Controls.Markdown#14]
Hello! Love your library and we are considering using it. However, SVG doesn't seem to render at all using the "inline image" syntax (even though jpg works). Is there a setting to get those to render properly?

Something like this should work, right?

```
![My Image](https://cdn.blahblahblah-public-cdn.com/my.svg)
```

**Comment by 0xc3u** [comment]
Hi,

We have fixed the issue with SVG rendering from an external URL in Version 1.0.18.

Example Markdown:

### Local SVG Image

![Local SVG](dotnet_bot.svg)

### Web Source SVG Image

![Web Source SVG](https://www.svgrepo.com/show/530402/honor.svg)

Thank you for bringing this to our attention!

---

Let me know if you need further adjustments!
