### ISSUE TITLE
support KaTeX

### ISSUE THREAD

**Issue by nicogis** [0xc3u/Indiko.Maui.Controls.Markdown#15]
Is there a possibility of KaTeX support for mathematical formulas?  ( https://learn.microsoft.com/en-en/azure/devops/project/wiki/markdown-guidance?view=azure-devops )

**Comment by 0xc3u** [comment]
We’re pleased to share that **KaTeX support for mathematical formulas** has been added in our latest release. You can now use KaTeX to render math expressions within Markdown using the following syntax:

```markdown
$$\int_0^\infty \mathrm{e}^{-x}\,\mathrm{d}x$$
```

This feature is available starting with **version 1.0.20**.

Thank you for your feedback, and we hope this addition enhances your experience!
