### ISSUE TITLE
Feature Request: Provide a property for Bullet spacing

### ISSUE THREAD

**Issue by logikonline** [0xc3u/Indiko.Maui.Controls.Markdown#17]
A nice update would be to allow us to control the spacing for the bullets.  The default spacing can appear somewhat distant, and the ability to control the pixel spacing would be ideal.

**Comment by 0xc3u** [comment]
We’re happy to let you know that the ability to control bullet spacing has been added! You can now adjust the spacing by setting the `ListIndent` property, which allows custom pixel spacing for bullets using `Thickness` values. For example:

```csharp
ListIndent="10,0,10,0"
```

This feature is available starting with **version 1.0.20**. We hope this helps you achieve the ideal look for your lists.

Thank you for your suggestion!
