### ISSUE TITLE
[Bug] Hyperlink colour has no effect

### ISSUE THREAD

**Issue by ClaytonIndustries** [0xc3u/Indiko.Maui.Controls.Markdown#18]
Set a hyperlink colour and notice that it does nothing. Tested on both Android and iOS

**Comment by 0xc3u** [comment]
Thank you for reporting this issue! The bug where setting a hyperlink color had no effect has been fixed in **version 1.0.21**. You should now be able to set hyperlink colors as expected on both Android and iOS.

We appreciate your feedback and patience!
