### ISSUE TITLE
KaTex inline

### ISSUE THREAD

**Issue by nicogis** [0xc3u/Indiko.Maui.Controls.Markdown#19]
Hi 0xc3u, I have tried it and it runs ok but if I have anwsers from chatgpt with mathematical symbol inline I don't see the conversion

I also have made replace char because in chatgpt use Latex:
For inline equations you use \\( and \\) for inline math equations and \\[ and \\] for block equations

Thank you

**Comment by 0xc3u** [comment]
Hi Nicogis,

Thank you for the feedback! We understand the need for inline mathematical symbols to display correctly. 
As of version 1.0.22, we’ve included initial support for LaTeX syntax processing to render inline and block equations.

Let us know if you need any additional assistance with the setup or have further suggestions!

Best regards,  
0xc3u
