### ISSUE TITLE
Feature Request: Create GitHub Release with auto generated changelog on every new release

### ISSUE THREAD

**Issue by thisisthekap** [0xc3u/Indiko.Maui.Controls.Markdown#24]

**Comment by 0xc3u** [comment]
Thank you for your feature request!

We’ve implemented a Semantic Release step in our CI workflow. With this update:

GitHub Release with Auto-Generated Changelog:
On every new release, a GitHub release will be created automatically, complete with a changelog generated from commit messages.

Updated Contribution Guidelines:
We’ve updated our contribution guidelines to include information on conventional commits. This ensures that commit messages are properly structured, allowing the changelog generation to reflect the changes accurately.

If you encounter any issues or have additional suggestions, feel free to reach out. Thank you for helping us improve!
