### ISSUE TITLE
Problem with ** __ etc

### ISSUE THREAD

**Issue by renelaerke** [0xc3u/Indiko.Maui.Controls.Markdown#4]
Hi,

thanx for this awesome component. Very good work.

However I just stumbled upon a problem. 

The default value set for the TextFontFace in the MarkdownView is set to "OpenSansRegular"

`
BindableProperty.Create(nameof(TextFontFace), typeof(string), typeof(MarkdownView), defaultValue: "OpenSansRegular", propertyChanged: OnMarkdownTextChanged);
`

Unfortunately this prevents the view from showing text in bold, italic etc. 

Btw. the sample project also sets the TextTypeFace value explicitly "OpenSansRegular" on the MainPage.xaml

Until you realise this problem it's a bit like "fighting windmills" when starting out with you component.

😉 René

**Comment by 0xc3u** [comment]
I will look into it René thank you for notice.

**Comment by 0xc3u** [comment]
We released a new version 1.0.6 please check the new version.
