### ISSUE TITLE
Single asterisks not rendering as italic

### ISSUE THREAD

**Issue by rdurfee** [0xc3u/Indiko.Maui.Controls.Markdown#7]
When text is surrounded by single asterisks, it should be rendered as italic, and instead the asterisks are displayed and the text is unformatted.

Single underline does work correctly for italics, but Markdown specifies you can use either for italic.

**Comment by 0xc3u** [comment]
Hi rdurfee

Thank you for pointing out the issue about the italics. 
We have fixed in the new version (1.0.9).
